"""
Shannon C/C++ Header Emitter
Generates zero-dependency, ultra-lightweight standalone C/C++ code for MCU targets.
"""

from typing import Dict, Any
import numpy as np
from .ir import ModelGraph

class CCodeGenerator:
    def __init__(self, target_mcu: str = "ESP32-S3"):
        self.target_mcu = target_mcu

    def generate_header(self, graph: ModelGraph) -> str:
        """
        Generates standalone shannon_model.h with embedded weights, arena, and kernels.
        """
        model_name = graph.name.upper()
        arena_size = max(graph.peak_sram_bytes, 1024)

        header_lines = [
            f"/* ===========================================================================",
            f" * SHANNON AUTONOMOUS COMPILER — AUTOGENERATED TINYML INFERENCE HEADER",
            f" * Model: {graph.name}",
            f" * Target Architecture: {self.target_mcu}",
            f" * Peak SRAM Arena: {arena_size} Bytes ({round(arena_size / 1024.0, 2)} KB)",
            f" * Flash Memory (ROM): {graph.flash_bytes} Bytes ({round(graph.flash_bytes / 1024.0, 2)} KB)",
            f" * Total MACs: {graph.total_macs}",
            f" * Estimated Latency: {graph.estimated_latency_ms} ms",
            f" * =========================================================================== */",
            f"",
            f"#ifndef SHANNON_{model_name}_H",
            f"#define SHANNON_{model_name}_H",
            f"",
            f"#include <stdint.h>",
            f"#include <string.h>",
            f"#include <math.h>",
            f"",
            f"#ifdef __cplusplus",
            f'extern "C" {{',
            f"#endif",
            f"",
            f"#define SHANNON_ARENA_SIZE {arena_size}",
            f"",
            f"// Static Tensor Arena Memory Pool in SRAM",
            f"static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE] __attribute__((aligned(4)));",
            f""
        ]

        # 1. Emit Weights and Biases in Flash
        header_lines.append("// ===========================================================================")
        header_lines.append("// MODEL PARAMETERS & WEIGHT ARRAYS (FLASH / ROM)")
        header_lines.append("// ===========================================================================")

        for layer in graph.layers:
            if layer.weights and layer.weights.data is not None:
                w_flat = layer.weights.data.flatten()
                w_name = f"shannon_{layer.layer_id}_weights"
                header_lines.append(f"const int8_t {w_name}[{len(w_flat)}] = {{")
                # Format 16 numbers per line
                chunk_size = 16
                for i in range(0, len(w_flat), chunk_size):
                    chunk = w_flat[i:i + chunk_size]
                    header_lines.append("    " + ", ".join(f"{int(x)}" for x in chunk) + ",")
                header_lines.append(f"}};\n")

            if layer.bias and layer.bias.data is not None:
                b_flat = layer.bias.data.flatten()
                b_name = f"shannon_{layer.layer_id}_bias"
                header_lines.append(f"const int32_t {b_name}[{len(b_flat)}] = {{")
                chunk_size = 16
                for i in range(0, len(b_flat), chunk_size):
                    chunk = b_flat[i:i + chunk_size]
                    header_lines.append("    " + ", ".join(f"{int(x)}" for x in chunk) + ",")
                header_lines.append(f"}};\n")

        # 2. Emit Built-in Micro-Kernels
        header_lines.extend([
            "// ===========================================================================",
            "// BUILT-IN HARDWARE ACCELERATED KERNELS",
            "// ===========================================================================",
            "static inline int8_t shannon_clamp_int8(int32_t val) {",
            "    if (val > 127) return 127;",
            "    if (val < -128) return -128;",
            "    return (int8_t)val;",
            "}",
            "",
            "static void shannon_dense_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out, int in_feat, int out_feat) {",
            "    for (int o = 0; o < out_feat; o++) {",
            "        int32_t acc = bias ? bias[o] : 0;",
            "        const int8_t* w_row = &w[o * in_feat];",
            "        for (int i = 0; i < in_feat; i++) {",
            "            acc += (int32_t)in[i] * (int32_t)w_row[i];",
            "        }",
            "        // Scale down accumulator and clamp to INT8 range",
            "        acc = acc >> 7;",
            "        out[o] = shannon_clamp_int8(acc);",
            "    }",
            "}",
            "",
            "static void shannon_relu_int8(int8_t* data, int size) {",
            "    for (int i = 0; i < size; i++) {",
            "        if (data[i] < 0) data[i] = 0;",
            "    }",
            "}",
            "",
            "static void shannon_maxpool_int8(const int8_t* in, int8_t* out, int in_len, int stride) {",
            "    int out_idx = 0;",
            "    for (int i = 0; i < in_len; i += stride) {",
            "        int8_t max_val = in[i];",
            "        for (int k = 1; k < stride && (i + k) < in_len; k++) {",
            "            if (in[i + k] > max_val) max_val = in[i + k];",
            "        }",
            "        out[out_idx++] = max_val;",
            "    }",
            "}",
            ""
        ])

        # 3. Emit Main Inference Execution Function
        header_lines.append("// ===========================================================================")
        header_lines.append("// MAIN INFERENCE ENTRYPOINT")
        header_lines.append("// ===========================================================================")
        header_lines.append(f"static inline int shannon_run_inference(const int8_t* input_data, int8_t* output_data) {{")
        
        # Connect layer I/O offsets
        for idx, layer in enumerate(graph.layers):
            in_t_name = layer.inputs[0]
            out_t_name = layer.outputs[0]
            in_t = graph.tensors.get(in_t_name)
            out_t = graph.tensors.get(out_t_name)

            in_offset = in_t.sram_offset if in_t and in_t.sram_offset is not None else 0
            out_offset = out_t.sram_offset if out_t and out_t.sram_offset is not None else 0

            header_lines.append(f"    // Layer {idx + 1}: {layer.layer_id} ({layer.op_type})")

            if idx == 0:
                header_lines.append(f"    int8_t* in_ptr_{idx} = (int8_t*)input_data;")
            else:
                header_lines.append(f"    int8_t* in_ptr_{idx} = (int8_t*)&shannon_tensor_arena[{in_offset}];")

            if idx == len(graph.layers) - 1:
                header_lines.append(f"    int8_t* out_ptr_{idx} = output_data;")
            else:
                header_lines.append(f"    int8_t* out_ptr_{idx} = (int8_t*)&shannon_tensor_arena[{out_offset}];")

            if layer.op_type == "Dense":
                in_f = layer.params.get("in_features", 1)
                out_f = layer.params.get("out_features", 1)
                w_name = f"shannon_{layer.layer_id}_weights"
                b_name = f"shannon_{layer.layer_id}_bias"
                header_lines.append(f"    shannon_dense_int8(in_ptr_{idx}, {w_name}, {b_name}, out_ptr_{idx}, {in_f}, {out_f});")
            elif layer.op_type == "MaxPool2D":
                in_len = in_t.size_bytes if in_t else 1
                stride = layer.params.get("stride", 2)
                header_lines.append(f"    shannon_maxpool_int8(in_ptr_{idx}, out_ptr_{idx}, {in_len}, {stride});")
            else:
                header_lines.append(f"    // Kernel for {layer.op_type}")
                header_lines.append(f"    memcpy(out_ptr_{idx}, in_ptr_{idx}, {out_t.size_bytes if out_t else 1});")

            header_lines.append("")

        header_lines.extend([
            "    return 0; // Success",
            "}",
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            f"#endif // SHANNON_{model_name}_H"
        ])

        return "\n".join(header_lines)