/**
 * Shannon STM32 CMSIS-NN Deployment Example
 * Bare-metal high-speed inference on ARM Cortex-M.
 */

#include <stdint.h>
#include <stdio.h>

// Include your autogenerated model header here
// #include "shannon_model.h"

int main(void)
{
    // Initialize system clock and hardware peripherals
    printf("⚡ Shannon STM32 Bare-Metal AI Runner Initialized\r\n");

    int8_t input_buffer[64] = {0};
    int8_t output_buffer[64] = {0};

    while (1) {
        // Run optimized inference loop
        // shannon_run_inference(input_buffer, output_buffer);
    }
    return 0;
}