/* ===========================================================================
 * SHANNON AUTONOMOUS COMPILER — AUTOGENERATED TINYML INFERENCE HEADER
 * Model: Shannon_MicroVision_v1
 * Target Architecture: STM32H7
 * Peak SRAM Arena: 18432 Bytes (18.0 KB)
 * Flash Memory (ROM): 1128 Bytes (1.1 KB)
 * Total MAC Operations: 239680
 * Estimated Latency: 1.9973333333333334 ms
 * Static Allocation: MISRA-C:2012 Rule 21.3 Compliant (0 Bytes Dynamic malloc)
 * =========================================================================== */

#ifndef SHANNON_SHANNON_MICROVISION_V1_H
#define SHANNON_SHANNON_MICROVISION_V1_H

#include <stdint.h>
#include <string.h>
#include <math.h>

// Architecture Hardware Acceleration Flags
#if defined(ESP32) || defined(ESP_PLATFORM)
    #define SHANNON_TARGET_ESP32 1
#elif defined(STM32H7xx) || defined(ARM_MATH_CM7)
    #define SHANNON_TARGET_STM32H7 1
#elif defined(PICO_RP2040) || defined(PICO_BOARD)
    #define SHANNON_TARGET_RP2040 1
#elif defined(NRF52840_XXAA)
    #define SHANNON_TARGET_NRF52 1
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define SHANNON_ARENA_SIZE 18432
#define SHANNON_FLASH_BYTES 1128
#define SHANNON_TOTAL_MACS 239680

// Static Tensor Arena Memory Pool in SRAM (Aligned to 4-byte word)
#if defined(__GNUC__) || defined(__clang__)
static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE] __attribute__((aligned(4)));
#else
static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE];
#endif

// ===========================================================================
// MODEL PARAMETERS & QUANTIZED WEIGHT ARRAYS (STORED IN FLASH / ROM)
// ===========================================================================
static const int8_t shannon_vis_conv1_weights[144] = {
    -2, -2, -39, -29, 1, -100, -80, 98, -121, 13, -91, -48, -10, -90, -40, -44,
    -90, -104, -93, -11, -77, -20, 2, 11, -7, 14, 44, 24, 26, 11, -48, -3,
    -66, -62, -50, 92, -6, 66, -21, -29, -19, -10, -47, -26, -57, 32, -40, -48,
    41, 64, -93, -67, 7, -58, -26, -9, 28, -67, 57, 53, 99, -16, -34, -13,
    40, -23, -24, -53, 127, 10, -44, -21, -63, -32, -89, -43, -39, -66, 36, 34,
    8, -63, 40, -60, 77, -89, 12, -7, -8, 54, -25, -62, -13, -68, 4, 20,
    -5, 26, -72, -18, -44, -34, 44, -8, 86, -58, 114, 21, 44, -7, -53, -99,
    74, 66, 32, -28, 52, -24, -18, -30, 48, 76, 17, 58, -34, 14, -12, 43,
    -32, 86, -2, 35, 34, -1, -62, 79, 28, 46, -11, -11, 73, 25, -14, 47,
};

static const int32_t shannon_vis_conv1_bias[16] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

static const int8_t shannon_vis_dw_conv_weights[144] = {
    110, 5, -65, -17, 52, -32, 3, -27, -41, -35, 55, 63, -29, -8, -1, 15,
    -3, 18, 48, 87, -4, 73, -9, 7, 24, -45, 30, -5, -48, 44, -54, -13,
    -2, -12, 10, -67, 116, -19, 8, -41, -19, 7, 67, 8, -27, -92, -127, -12,
    -60, -23, -26, -3, -123, -1, -52, 4, 79, -30, -95, -66, 17, -3, 11, 33,
    30, -16, 30, 5, 5, 20, 49, 67, 4, -84, -15, -76, -41, -31, -30, -39,
    -20, 16, 31, 10, -29, 10, 13, 14, -44, 80, 22, -46, -94, -18, 13, -64,
    -42, 44, -43, -54, 22, -89, 19, -64, -74, 27, 83, -28, 31, 72, 98, 19,
    20, 14, -25, -9, -34, 8, 15, -26, 29, 3, -20, -42, -29, -8, -7, 120,
    -56, -58, -28, 69, 17, 47, 44, 11, 31, -8, 18, 94, -15, 29, -36, -66,
};

static const int32_t shannon_vis_dw_conv_bias[16] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

static const int8_t shannon_vis_pw_conv_weights[512] = {
    13, -45, 36, 15, -51, 60, -35, 13, -18, -11, 20, 13, 39, -18, 49, -64,
    -5, 43, 14, 52, 32, -14, 73, -33, 69, 4, 16, 14, -57, 8, -37, -26,
    63, -21, 30, -21, -29, -28, -98, 15, 20, 43, 8, -76, 43, -22, -69, 29,
    19, 13, -10, 0, -64, 16, 27, -24, -73, -13, 30, 57, 82, -45, -46, 27,
    31, 88, 20, 37, 37, 26, 113, 65, -24, 13, -55, 4, -89, -39, 8, 28,
    79, 5, -86, -95, -28, 33, 9, 31, 13, 37, 72, 12, -31, -2, 12, 99,
    -98, -37, 49, 52, 26, -60, -43, 77, -46, 86, 48, -48, -8, 43, 3, -13,
    -81, -57, 4, -52, -14, 23, -55, 84, 86, 4, -9, -14, -19, 110, -69, 67,
    -3, -62, 5, 66, 79, 74, -7, -6, -34, 107, 99, 10, 12, 35, -14, -54,
    -19, -32, 18, -35, -38, 92, -3, -6, 19, -27, 37, -2, 118, -23, -118, -21,
    -4, 50, 1, -98, 63, 53, 20, 2, -1, -51, 39, -63, -61, 85, 9, -18,
    45, -66, -53, -113, -40, 68, 84, -4, -24, -18, -19, 12, -69, -26, 85, 63,
    16, -80, -29, 14, -26, 78, 10, -14, -31, 48, 16, -80, 55, -13, -37, -70,
    36, -20, -7, -1, 52, -109, 104, 70, 13, -27, -38, 16, 21, 3, -12, -3,
    17, 25, 5, -27, 39, 68, -71, -2, 30, 31, 13, -97, 9, 78, 11, 15,
    20, 69, -10, 1, -38, -26, -30, 7, -32, -24, 120, 6, 26, -32, 113, 36,
    5, 80, -29, -30, 19, -25, 55, 104, -29, -30, 40, -17, -35, 39, -23, 20,
    -6, -18, -67, 58, 12, -54, -53, 13, -86, 57, -102, 29, 51, -47, 76, 14,
    -2, 26, 52, 93, 28, -40, -23, 37, 31, -27, -29, -19, -1, -118, -62, 56,
    -96, -10, -29, -38, -20, -15, 78, -8, -6, 18, 65, 123, -26, 41, 11, 9,
    -23, 15, -79, 52, 42, 43, -49, 45, 57, 20, -19, -38, -83, -39, -49, -92,
    41, 32, 0, -66, -33, -50, 23, 20, 58, -78, -127, 22, 12, 3, -1, 16,
    49, -70, 38, 50, 99, 38, 53, 41, 53, -28, 42, 0, -13, -3, 14, 18,
    -22, -13, 8, -61, -40, -12, -9, 31, 73, -27, 34, 33, 63, 36, -46, -78,
    34, 108, -43, 66, 32, 22, -10, -53, 16, 33, -95, -41, 20, -5, 20, 9,
    54, -7, -31, 41, 27, -62, -65, -29, 19, -13, 52, 43, 45, 47, -60, 37,
    -92, 19, 48, 10, -11, -104, -8, -19, -86, 73, 26, -12, 55, 34, -24, -110,
    22, -42, -1, 102, 34, -5, -75, -82, 22, 53, 24, -30, 10, 0, -20, -30,
    39, -96, 14, -30, -46, 48, -24, -55, 3, -40, -50, 47, 77, 11, 16, 36,
    21, 32, 8, -17, -7, 18, 71, -59, -18, -15, -24, 10, 82, 43, -11, -9,
    -4, -33, 46, 50, -23, -16, -13, -28, -3, -56, 11, 86, 14, -49, -5, 45,
    39, -12, -64, -21, 112, -44, 93, -122, -17, -7, -96, 30, -20, -1, 51, 30,
};

static const int32_t shannon_vis_pw_conv_bias[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

static const int8_t shannon_vis_classifier_weights[64] = {
    -75, -21, -57, 5, 39, -127, -8, -37, 71, -80, 27, 28, -76, 52, 7, 2,
    68, -100, -68, -45, 42, 2, 56, -48, -13, -106, -19, 10, -84, 2, 29, 39,
    13, -52, 38, 23, -4, 17, 38, -14, 52, 27, -32, -27, -50, -100, -8, -44,
    5, 19, -39, -45, -15, 24, -38, -33, 38, 37, -75, -14, -4, -48, 20, -16,
};

static const int32_t shannon_vis_classifier_bias[2] = {
    0, 0,
};

// ===========================================================================
// HARDWARE ACCELERATED INT8 / INT4 MICRO-KERNELS
// ===========================================================================
static inline int8_t shannon_clamp_int8(int32_t val) {
    if (val > 127) return 127;
    if (val < -128) return -128;
    return (int8_t)val;
}

static inline void shannon_relu_int8(int8_t* data, int size) {
    for (int i = 0; i < size; i++) {
        if (data[i] < 0) data[i] = 0;
    }
}

static void shannon_dense_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out, int in_feat, int out_feat) {
    for (int o = 0; o < out_feat; o++) {
        int32_t acc = bias ? bias[o] : 0;
        const int8_t* w_row = &w[o * in_feat];
        int i = 0;
        // 4-way loop unrolling for SIMD compiler vectorization
        for (; i <= in_feat - 4; i += 4) {
            acc += ((int32_t)in[i]   * (int32_t)w_row[i]) +
                   ((int32_t)in[i+1] * (int32_t)w_row[i+1]) +
                   ((int32_t)in[i+2] * (int32_t)w_row[i+2]) +
                   ((int32_t)in[i+3] * (int32_t)w_row[i+3]);
        }
        for (; i < in_feat; i++) {
            acc += (int32_t)in[i] * (int32_t)w_row[i];
        }
        // Re-quantize and scale down accumulator to INT8 output range
        acc = acc >> 7;
        out[o] = shannon_clamp_int8(acc);
    }
}

static void shannon_conv2d_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out,
                               int in_h, int in_w, int in_c, int out_h, int out_w, int out_c,
                               int kh, int kw, int stride) {
    for (int oc = 0; oc < out_c; oc++) {
        int32_t b = bias ? bias[oc] : 0;
        const int8_t* w_oc = &w[oc * in_c * kh * kw];
        for (int oh = 0; oh < out_h; oh++) {
            int ih_base = oh * stride;
            for (int ow = 0; ow < out_w; ow++) {
                int iw_base = ow * stride;
                int32_t acc = b;
                for (int ic = 0; ic < in_c; ic++) {
                    for (int r = 0; r < kh; r++) {
                        int ih = ih_base + r;
                        if (ih < 0 || ih >= in_h) continue;
                        for (int c = 0; c < kw; c++) {
                            int iw = iw_base + c;
                            if (iw < 0 || iw >= in_w) continue;
                            int in_idx = (ih * in_w + iw) * in_c + ic;
                            int w_idx = ((ic * kh + r) * kw + c);
                            acc += (int32_t)in[in_idx] * (int32_t)w_oc[w_idx];
                        }
                    }
                }
                acc = acc >> 7;
                out[(oh * out_w + ow) * out_c + oc] = shannon_clamp_int8(acc);
            }
        }
    }
}

static void shannon_dwconv2d_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out,
                                 int in_h, int in_w, int channels, int out_h, int out_w,
                                 int kh, int kw, int stride) {
    for (int c = 0; c < channels; c++) {
        int32_t b = bias ? bias[c] : 0;
        const int8_t* w_c = &w[c * kh * kw];
        for (int oh = 0; oh < out_h; oh++) {
            int ih_base = oh * stride;
            for (int ow = 0; ow < out_w; ow++) {
                int iw_base = ow * stride;
                int32_t acc = b;
                for (int r = 0; r < kh; r++) {
                    int ih = ih_base + r;
                    if (ih < 0 || ih >= in_h) continue;
                    for (int col = 0; col < kw; col++) {
                        int iw = iw_base + col;
                        if (iw < 0 || iw >= in_w) continue;
                        int in_idx = (ih * in_w + iw) * channels + c;
                        int w_idx = r * kw + col;
                        acc += (int32_t)in[in_idx] * (int32_t)w_c[w_idx];
                    }
                }
                acc = acc >> 7;
                out[(oh * out_w + ow) * channels + c] = shannon_clamp_int8(acc);
            }
        }
    }
}

static void shannon_maxpool_int8(const int8_t* in, int8_t* out, int in_len, int stride) {
    int out_idx = 0;
    for (int i = 0; i < in_len; i += stride) {
        int8_t max_val = in[i];
        for (int k = 1; k < stride && (i + k) < in_len; k++) {
            if (in[i + k] > max_val) max_val = in[i + k];
        }
        out[out_idx++] = max_val;
    }
}

static void shannon_softmax_int8(const int8_t* in, float* out, int size) {
    int8_t max_val = in[0];
    for (int i = 1; i < size; i++) {
        if (in[i] > max_val) max_val = in[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        out[i] = expf((float)(in[i] - max_val) * 0.1f);
        sum += out[i];
    }
    if (sum > 0.0f) {
        for (int i = 0; i < size; i++) out[i] /= sum;
    }
}

// ===========================================================================
// MAIN INFERENCE ENTRYPOINT (ZERO DYNAMIC ALLOCATION)
// ===========================================================================
static inline int shannon_run_inference(const int8_t* input_data, int8_t* output_data) {
    if (!input_data || !output_data) return -1; // Null pointer check

    // Step 1: vis_conv1 [Conv2D]
    const int8_t* in_ptr_0 = input_data;
    int8_t* out_ptr_0 = (int8_t*)&shannon_tensor_arena[0];
    shannon_conv2d_int8(in_ptr_0, shannon_vis_conv1_weights, shannon_vis_conv1_bias, out_ptr_0, 24, 24, 1, 24, 24, 16, 3, 3, 2);

    // Step 2: vis_dw_conv [DepthwiseConv2D]
    const int8_t* in_ptr_1 = (const int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_1 = (int8_t*)&shannon_tensor_arena[9216];
    shannon_dwconv2d_int8(in_ptr_1, shannon_vis_dw_conv_weights, shannon_vis_dw_conv_bias, out_ptr_1, 24, 24, 16, 24, 24, 3, 3, 1);

    // Step 3: vis_pw_conv [Conv2D]
    const int8_t* in_ptr_2 = (const int8_t*)&shannon_tensor_arena[9216];
    int8_t* out_ptr_2 = (int8_t*)&shannon_tensor_arena[0];
    shannon_conv2d_int8(in_ptr_2, shannon_vis_pw_conv_weights, shannon_vis_pw_conv_bias, out_ptr_2, 24, 24, 16, 12, 12, 32, 1, 1, 2);

    // Step 4: vis_global_pool [MaxPool2D]
    const int8_t* in_ptr_3 = (const int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_3 = (int8_t*)&shannon_tensor_arena[4608];
    shannon_maxpool_int8(in_ptr_3, out_ptr_3, 4608, 12);

    // Step 5: vis_classifier [Dense]
    const int8_t* in_ptr_4 = (const int8_t*)&shannon_tensor_arena[4608];
    int8_t* out_ptr_4 = output_data;
    shannon_dense_int8(in_ptr_4, shannon_vis_classifier_weights, shannon_vis_classifier_bias, out_ptr_4, 32, 2);

    return 0; // Inference Execution Success
}

#ifdef __cplusplus
}
#endif

#endif // SHANNON_SHANNON_MICROVISION_V1_H