/* ===========================================================================
 * SHANNON AUTONOMOUS COMPILER — AUTOGENERATED TINYML INFERENCE HEADER
 * Model: Shannon_MicroVision_v1
 * Target Architecture: STM32H7
 * Peak SRAM Arena: 18432 Bytes (18.0 KB)
 * Flash Memory (ROM): 1128 Bytes (1.1 KB)
 * Total MACs: 239680
 * Estimated Latency: 1.9973333333333334 ms
 * =========================================================================== */

#ifndef SHANNON_SHANNON_MICROVISION_V1_H
#define SHANNON_SHANNON_MICROVISION_V1_H

#include <stdint.h>
#include <string.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SHANNON_ARENA_SIZE 18432

// Static Tensor Arena Memory Pool in SRAM
static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE] __attribute__((aligned(4)));

// ===========================================================================
// MODEL PARAMETERS & WEIGHT ARRAYS (FLASH / ROM)
// ===========================================================================
const int8_t shannon_vis_conv1_weights[144] = {
    17, -127, -60, 51, 7, 50, 26, -40, -95, -76, 5, -55, 89, -87, 62, -26,
    25, -58, 40, 54, -20, 32, 36, 54, -52, 76, -25, -17, -98, 37, -45, 41,
    -51, -93, 6, 47, 45, -34, -32, -33, 3, 73, 104, 95, 49, -35, 56, -58,
    -28, 34, -1, 15, 49, 22, 118, 55, -15, 84, 18, -115, -23, -12, 15, 12,
    -56, 58, -38, 35, -67, 38, 48, 70, 30, -55, 72, 17, 11, -52, 11, 27,
    -9, -37, -73, -41, 73, -42, 51, 69, -12, -24, 37, 49, 22, -44, -25, 98,
    3, 21, -22, 37, -31, -3, 10, 58, 46, 11, 77, 52, 37, 41, 34, -17,
    -15, -13, -4, -52, -28, 85, -23, -41, -53, 38, 35, 28, 39, 5, 13, 44,
    -94, 33, 34, 28, 30, 83, -17, -25, -8, 58, -91, 7, 32, 46, -81, 5,
};

const int32_t shannon_vis_conv1_bias[16] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

const int8_t shannon_vis_dw_conv_weights[144] = {
    -73, -42, -35, -36, 39, 32, -45, 8, 16, 34, -31, 20, -27, 50, 7, 65,
    -13, 8, -3, -54, -56, -17, -29, -5, -21, -31, -8, -18, 40, -41, -1, -16,
    58, -127, 31, -7, -12, -11, 41, -35, 37, 36, -68, -28, -17, -53, 13, -5,
    31, -42, -18, 43, 51, 12, -51, 38, -8, -64, -26, 60, -5, -27, -51, 5,
    7, 76, 18, 21, 45, -9, -7, -39, 34, -41, 2, -60, -30, 49, 36, -3,
    -70, 2, 31, 21, 26, 1, 2, 53, -59, -9, 12, 7, 10, 13, 113, 19,
    -9, 29, 1, 6, -49, 31, -15, -5, 22, -25, 39, -41, 39, -22, -25, -11,
    -8, 0, -21, -16, -56, -20, -10, 0, 61, -13, -41, 0, 31, 77, -29, -64,
    -33, -51, 16, 3, 35, -44, -18, 32, 55, 19, -19, -10, -21, -18, 6, -2,
};

const int32_t shannon_vis_dw_conv_bias[16] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

const int8_t shannon_vis_pw_conv_weights[512] = {
    -11, -84, -29, -18, 29, 8, 34, 46, -26, -42, 59, -5, -17, 3, 22, -88,
    52, 18, -16, 11, 36, -5, 1, 28, 10, -82, 43, -28, -9, -55, -29, 32,
    14, 24, 71, -39, 32, 19, -52, -37, 49, 78, 97, -32, -32, 56, 62, 38,
    -12, 7, 38, -31, -5, 12, 19, -42, -27, -41, -28, 83, -9, -110, -27, 28,
    20, -4, -55, -27, -34, -49, -17, -18, -64, 25, -40, 42, -2, -22, 26, 2,
    -24, -82, 50, -55, 7, -2, 9, 7, 28, -12, -60, -17, 2, 55, -21, 50,
    16, -4, 35, -28, 30, -20, -82, -5, -27, 7, -28, -39, 16, -32, 15, 12,
    -36, 29, 5, -8, 56, -18, -1, -13, 15, 13, 60, -51, -44, -7, 24, -6,
    -80, 14, 6, 52, -3, -43, -6, -3, -70, -21, 35, -12, 27, -36, -35, 13,
    37, 29, 4, -54, -36, -2, 12, -4, -27, 11, 28, -17, 34, 38, 49, 46,
    -51, 29, 9, -37, -66, -17, -24, -23, 5, 49, -9, 33, -35, 70, 43, -38,
    20, -45, 2, -26, -38, -21, -30, -77, 30, -19, -35, 33, 34, 11, -26, 21,
    -33, -15, 13, -47, -69, -55, -38, -37, 53, 66, -19, -85, 21, 46, -2, 6,
    -29, -43, 24, -20, 27, -65, 13, 32, 32, -49, -15, 16, -41, 5, -19, 67,
    20, 44, 3, 25, 33, 15, -47, -26, -77, -61, -32, 18, -13, -32, 18, 19,
    -51, -13, -12, 63, -72, 127, 36, 23, -47, 10, -31, -45, -52, 44, 102, -8,
    18, 48, -59, -3, -11, -27, 33, 42, -20, -70, 50, 26, 41, 14, 3, -67,
    -30, 23, 0, -33, -43, -19, 0, -28, -21, -15, -92, 18, 48, -38, 58, -41,
    22, -33, -30, 5, -17, -17, 68, 18, -52, 4, 21, -6, -4, 59, 12, 24,
    1, 43, 18, -46, 11, -26, -7, 11, -15, -1, 5, 8, -17, -39, 2, -16,
    22, -13, -26, -22, -5, 33, 0, -22, 50, 4, -35, 23, 15, 24, 39, 75,
    49, -39, -3, -40, 10, -38, 23, 14, 70, 1, 22, 78, 22, 28, -59, -12,
    19, -19, -79, 37, 10, -23, 23, -6, -2, -21, -26, -63, -34, 21, -62, -27,
    5, 9, -31, -35, 63, -57, -21, 33, -23, -5, 2, -10, 48, 63, -54, 6,
    -62, 55, -12, 18, -13, -3, -13, -45, -18, 37, 14, -16, -20, -103, -57, 16,
    45, 23, 44, 27, 20, 73, -41, -50, -74, -12, 14, 45, -33, 10, 37, 58,
    -4, -1, -38, 24, -2, 79, 43, 5, -1, 40, -35, 44, -3, 43, 40, -23,
    -56, -31, 7, 43, -66, 2, 25, 27, 21, 58, 37, 39, 66, 15, -14, -12,
    12, 70, 19, 12, -8, -38, -45, -55, 37, -21, 49, 37, -47, 5, 15, -4,
    22, -34, -26, 18, -24, 22, -26, -10, -55, 12, 47, 29, 11, -23, -3, -43,
    9, -29, 1, -23, 4, 12, -14, 7, -40, 3, 31, 3, 37, -5, 9, 56,
    -33, -5, 59, 29, -42, 6, 11, -24, 30, -3, 7, -11, 5, 28, 8, -50,
};

const int32_t shannon_vis_pw_conv_bias[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

const int8_t shannon_vis_classifier_weights[64] = {
    -15, -1, 5, 25, -91, 47, -52, -7, 51, -41, 35, -15, -8, 23, 6, -91,
    -127, 13, 76, -29, -45, 32, 21, -19, -50, -49, 58, -55, -21, -2, -15, 52,
    4, -30, 54, 97, -69, -3, 11, 39, 43, 40, 10, 25, 33, 11, 6, -30,
    83, 4, -95, -55, 7, 3, 15, -20, -76, -64, -43, 19, 61, -27, -76, 51,
};

const int32_t shannon_vis_classifier_bias[2] = {
    0, 0,
};

// ===========================================================================
// BUILT-IN HARDWARE ACCELERATED KERNELS
// ===========================================================================
static inline int8_t shannon_clamp_int8(int32_t val) {
    if (val > 127) return 127;
    if (val < -128) return -128;
    return (int8_t)val;
}

static void shannon_dense_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out, int in_feat, int out_feat) {
    for (int o = 0; o < out_feat; o++) {
        int32_t acc = bias ? bias[o] : 0;
        const int8_t* w_row = &w[o * in_feat];
        for (int i = 0; i < in_feat; i++) {
            acc += (int32_t)in[i] * (int32_t)w_row[i];
        }
        // Scale down accumulator and clamp to INT8 range
        acc = acc >> 7;
        out[o] = shannon_clamp_int8(acc);
    }
}

static void shannon_relu_int8(int8_t* data, int size) {
    for (int i = 0; i < size; i++) {
        if (data[i] < 0) data[i] = 0;
    }
}

static void shannon_maxpool_int8(const int8_t* in, int8_t* out, int in_len, int stride) {
    int out_idx = 0;
    for (int i = 0; i < in_len; i += stride) {
        int8_t max_val = in[i];
        for (int k = 1; k < stride && (i + k) < in_len; k++) {
            if (in[i + k] > max_val) max_val = in[i + k];
        }
        out[out_idx++] = max_val;
    }
}

// ===========================================================================
// MAIN INFERENCE ENTRYPOINT
// ===========================================================================
static inline int shannon_run_inference(const int8_t* input_data, int8_t* output_data) {
    // Layer 1: vis_conv1 (Conv2D)
    int8_t* in_ptr_0 = (int8_t*)input_data;
    int8_t* out_ptr_0 = (int8_t*)&shannon_tensor_arena[0];
    // Kernel for Conv2D
    memcpy(out_ptr_0, in_ptr_0, 9216);

    // Layer 2: vis_dw_conv (DepthwiseConv2D)
    int8_t* in_ptr_1 = (int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_1 = (int8_t*)&shannon_tensor_arena[9216];
    // Kernel for DepthwiseConv2D
    memcpy(out_ptr_1, in_ptr_1, 9216);

    // Layer 3: vis_pw_conv (Conv2D)
    int8_t* in_ptr_2 = (int8_t*)&shannon_tensor_arena[9216];
    int8_t* out_ptr_2 = (int8_t*)&shannon_tensor_arena[0];
    // Kernel for Conv2D
    memcpy(out_ptr_2, in_ptr_2, 4608);

    // Layer 4: vis_global_pool (MaxPool2D)
    int8_t* in_ptr_3 = (int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_3 = (int8_t*)&shannon_tensor_arena[4608];
    shannon_maxpool_int8(in_ptr_3, out_ptr_3, 4608, 12);

    // Layer 5: vis_classifier (Dense)
    int8_t* in_ptr_4 = (int8_t*)&shannon_tensor_arena[4608];
    int8_t* out_ptr_4 = output_data;
    shannon_dense_int8(in_ptr_4, shannon_vis_classifier_weights, shannon_vis_classifier_bias, out_ptr_4, 32, 2);

    return 0; // Success
}

#ifdef __cplusplus
}
#endif

#endif // SHANNON_SHANNON_MICROVISION_V1_H