/* ===========================================================================
 * SHANNON AUTONOMOUS COMPILER — AUTOGENERATED TINYML INFERENCE HEADER
 * Model: Shannon_MicroVision_Real
 * Target Architecture: STM32H7
 * Peak SRAM Arena: 18432 Bytes (18.0 KB)
 * Flash Memory (ROM): 1128 Bytes (1.1 KB)
 * Total MAC Operations: 239680
 * Estimated Latency: 1.9973333333333334 ms
 * Static Allocation: MISRA-C:2012 Rule 21.3 Compliant (0 Bytes Dynamic malloc)
 * =========================================================================== */

#ifndef SHANNON_SHANNON_MICROVISION_REAL_H
#define SHANNON_SHANNON_MICROVISION_REAL_H

#include <stdint.h>
#include <string.h>
#include <math.h>

// Architecture Hardware Acceleration Flags
#if defined(ESP32) || defined(ESP_PLATFORM)
    #define SHANNON_TARGET_ESP32 1
#elif defined(STM32H7xx) || defined(ARM_MATH_CM7)
    #define SHANNON_TARGET_STM32H7 1
#elif defined(PICO_RP2040) || defined(PICO_BOARD)
    #define SHANNON_TARGET_RP2040 1
#elif defined(NRF52840_XXAA)
    #define SHANNON_TARGET_NRF52 1
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define SHANNON_ARENA_SIZE 18432
#define SHANNON_FLASH_BYTES 1128
#define SHANNON_TOTAL_MACS 239680

// Static Tensor Arena Memory Pool in SRAM (Aligned to 4-byte word)
#if defined(__GNUC__) || defined(__clang__)
static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE] __attribute__((aligned(4)));
#else
static uint8_t shannon_tensor_arena[SHANNON_ARENA_SIZE];
#endif

// ===========================================================================
// MODEL PARAMETERS & QUANTIZED WEIGHT ARRAYS (STORED IN FLASH / ROM)
// ===========================================================================
static const int8_t shannon_vis_conv1_weights[144] = {
    93, 97, 34, 103, 38, 61, 21, 84, 99, 13, 98, 62, 96, 59, 59, 52,
    66, 42, -19, 21, -19, 1, -15, 43, -38, -18, -9, -47, -5, -35, 16, -50,
    39, -24, -33, 30, -1, 36, -2, -26, 5, -25, 15, 40, 23, -31, 26, 21,
    22, -26, -48, -13, -39, 40, 90, 98, 90, 74, 118, 33, 78, 36, 89, 3,
    4, -10, 57, 14, -12, 10, 77, 19, 54, -46, -56, -44, -38, 23, 20, 47,
    -29, -21, 43, -8, 47, 11, 53, -20, 2, 39, 51, 33, 62, 62, -35, -45,
    79, 10, -27, -104, -83, -36, -58, -91, -49, -89, -97, -81, -127, -113, -25, -71,
    -64, -119, -119, -90, -73, -95, -75, -65, -59, -75, -56, -88, -86, -69, -21, -44,
    45, -15, 43, 17, -49, 34, -18, -3, -20, -29, 46, 22, 51, -2, 73, -2,
};

static const int32_t shannon_vis_conv1_bias[16] = {
    -4161, -1134, 2210, 9839, 4625, -5264, -5541, -6837, -617, -6081, 1081, 335, 1369, -2098, 1659, -5882,
};

static const int8_t shannon_vis_dw_conv_weights[144] = {
    103, 63, 56, 0, 73, 39, 24, 100, 61, -61, -71, -45, 19, -64, -48, 2,
    -71, 63, 36, -60, 6, 22, 3, -27, 22, 22, 14, 41, 31, 47, 41, 34,
    83, 93, 36, 24, -6, -10, 7, 8, -58, -27, 40, 15, -9, -37, -30, -45,
    -12, 22, 42, 32, -45, -32, 66, 127, 80, 59, 97, 50, 36, 114, 44, -75,
    -121, -28, 23, 50, -84, -118, -98, -24, 27, 48, 30, 14, -1, -43, -48, -53,
    23, -80, -77, -82, -56, -30, -15, -54, -77, -29, -18, -24, 11, -35, -2, -41,
    30, -25, 48, 80, 95, 16, 94, 28, 80, 105, 46, 58, 60, 25, 97, 14,
    104, 109, 123, 55, 21, -40, -7, -62, -63, -69, -20, -79, -63, -46, -61, 38,
    39, -14, -14, -31, -57, -63, 14, -68, -84, -42, -1, 2, -36, -57, -55, -73,
};

static const int32_t shannon_vis_dw_conv_bias[16] = {
    -6867, 6403, -2981, 4469, -2788, 4712, 135, 8223, -4893, 8024, 9797, 1246, 7937, 7894, -1677, 5521,
};

static const int8_t shannon_vis_pw_conv_weights[512] = {
    -24, -7, 26, 18, -22, -28, -24, -34, -27, -9, 23, 6, -26, -28, 17, -26,
    -4, 17, -16, -4, -3, -8, -18, -31, -28, -19, 34, -17, -23, 8, 10, 19,
    12, 32, -34, 32, 21, 24, -12, 63, -13, 10, -6, 35, 43, -1, 7, 5,
    -30, -14, 36, 62, -28, 35, 4, 30, 6, 61, 70, 11, 65, -14, 20, 72,
    0, 32, -30, -13, 20, -8, -7, -14, 24, 17, 11, -19, -28, 4, 10, -16,
    25, 44, -5, -3, 2, -29, -42, -20, -18, 12, -8, -31, 10, 52, 17, -19,
    19, 49, -30, -10, 8, 2, -39, 29, 28, 17, 10, -35, -17, 44, 10, 6,
    -21, 31, -21, 44, -13, 21, 11, 25, -10, 45, 16, 62, 72, -59, -15, 51,
    71, 6, 2, -55, -25, 4, 61, -41, -9, -2, -23, -19, -8, 27, 4, -58,
    57, 18, -29, -37, 33, 24, 74, -12, 26, -30, -42, 33, -17, -25, -11, -20,
    49, 16, -20, -19, -20, -33, 42, -34, 32, -2, -10, 29, 3, -7, -3, -36,
    47, 59, -9, -24, -8, -10, 37, -2, 27, -8, -30, 10, 4, 3, 3, -57,
    49, -45, -22, -50, 27, -36, 54, -36, -4, -19, -29, 11, 21, -29, 13, -36,
    46, 42, 8, -35, -4, 31, 51, -33, -33, -37, -40, 47, -17, -2, -8, -33,
    0, -10, 25, 63, 20, 20, -9, 61, -9, 53, 32, 11, 50, -2, 23, 71,
    24, 33, 2, -30, -24, -22, -31, -17, -32, -32, -21, -34, -21, 13, 29, -10,
    38, 43, -21, -41, 30, -37, 55, -13, 6, -23, -50, -8, -13, 33, 6, -1,
    24, 21, -20, -59, 6, -42, 76, -47, -19, -20, -72, -15, -25, -13, -31, -42,
    73, 59, 18, -43, -15, 29, 61, -43, 5, -60, -39, 35, -15, 21, -36, -50,
    -1, -22, -4, 14, -34, 10, -23, -17, 13, 28, -9, -14, -31, -18, -30, -8,
    -5, -31, 30, 14, -34, -25, 1, -5, -4, -21, 21, -25, 21, -6, 7, 22,
    -17, -34, -1, 73, -34, 52, -4, 67, 13, 48, 58, 47, 65, -15, 3, 63,
    29, 12, -25, 21, -8, -13, -37, -11, 25, 0, -25, 5, -16, 27, -30, -16,
    17, -3, 8, 0, 15, 14, 58, -29, 28, -9, -59, 6, -9, 7, -25, -65,
    -10, -50, 14, 47, -24, 41, -4, 57, 20, 5, 63, 70, 52, -34, -19, 29,
    41, 57, 9, 12, -4, 20, 63, -76, -34, -51, 0, -32, -31, 49, 10, -4,
    -27, -37, 22, 62, 13, 29, 7, 77, -22, 17, 62, 5, 11, 17, 18, 42,
    36, 28, 28, -32, 8, 23, 25, -3, -17, -34, -24, -20, -26, 39, 2, -59,
    26, 52, 9, -9, -13, -23, 43, -47, -24, -27, -26, -14, -13, 9, 2, -15,
    -20, -102, 18, 90, -18, 107, -3, 116, 18, 63, 102, 64, 76, 7, -23, 127,
    -11, 3, -26, 50, -19, -5, -1, 58, 30, 9, 18, 32, 37, 4, 26, 21,
    126, 46, -9, -8, 17, 16, 79, -68, -10, -48, -5, -44, -4, -6, 21, -56,
};

static const int32_t shannon_vis_pw_conv_bias[32] = {
    -3039, -1909, -108, 4882, -2326, -67, 1610, -631, 1105, -3314, -3157, -2147, -1004, -1073, 2709, -642,
    1382, 2480, 1536, -1367, -4020, 4796, -2194, 237, 5046, 2064, 4755, 3810, 438, 4825, 4352, -3068,
};

static const int8_t shannon_vis_classifier_weights[64] = {
    -12, -9, 21, -10, 61, -48, 54, -56, 2, 22, -52, 44, -50, 70, 88, -64,
    -39, 50, -41, 51, -51, 22, -43, 36, -34, 47, -45, 33, 55, -58, -4, 22,
    -23, 54, -31, 53, -41, 69, 16, -10, 10, 1, 74, -42, 14, 1, -28, 17,
    23, -65, -38, 50, 21, -36, -23, 17, -36, 56, 107, -113, 37, -27, -104, 127,
};

static const int32_t shannon_vis_classifier_bias[2] = {
    -734, -391,
};

// ===========================================================================
// HARDWARE ACCELERATED INT8 / INT4 MICRO-KERNELS
// ===========================================================================
static inline int8_t shannon_clamp_int8(int32_t val) {
    if (val > 127) return 127;
    if (val < -128) return -128;
    return (int8_t)val;
}

static inline void shannon_relu_int8(int8_t* data, int size) {
    for (int i = 0; i < size; i++) {
        if (data[i] < 0) data[i] = 0;
    }
}

static void shannon_dense_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out, int in_feat, int out_feat) {
    for (int o = 0; o < out_feat; o++) {
        int32_t acc = bias ? bias[o] : 0;
        const int8_t* w_row = &w[o * in_feat];
        int i = 0;
        // 4-way loop unrolling for SIMD compiler vectorization
        for (; i <= in_feat - 4; i += 4) {
            acc += ((int32_t)in[i]   * (int32_t)w_row[i]) +
                   ((int32_t)in[i+1] * (int32_t)w_row[i+1]) +
                   ((int32_t)in[i+2] * (int32_t)w_row[i+2]) +
                   ((int32_t)in[i+3] * (int32_t)w_row[i+3]);
        }
        for (; i < in_feat; i++) {
            acc += (int32_t)in[i] * (int32_t)w_row[i];
        }
        // Re-quantize and scale down accumulator to INT8 output range
        acc = acc >> 7;
        out[o] = shannon_clamp_int8(acc);
    }
}

static void shannon_conv2d_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out,
                               int in_h, int in_w, int in_c, int out_h, int out_w, int out_c,
                               int kh, int kw, int stride) {
    for (int oc = 0; oc < out_c; oc++) {
        int32_t b = bias ? bias[oc] : 0;
        const int8_t* w_oc = &w[oc * in_c * kh * kw];
        for (int oh = 0; oh < out_h; oh++) {
            int ih_base = oh * stride;
            for (int ow = 0; ow < out_w; ow++) {
                int iw_base = ow * stride;
                int32_t acc = b;
                for (int ic = 0; ic < in_c; ic++) {
                    for (int r = 0; r < kh; r++) {
                        int ih = ih_base + r;
                        if (ih < 0 || ih >= in_h) continue;
                        for (int c = 0; c < kw; c++) {
                            int iw = iw_base + c;
                            if (iw < 0 || iw >= in_w) continue;
                            int in_idx = (ih * in_w + iw) * in_c + ic;
                            int w_idx = ((ic * kh + r) * kw + c);
                            acc += (int32_t)in[in_idx] * (int32_t)w_oc[w_idx];
                        }
                    }
                }
                acc = acc >> 7;
                out[(oh * out_w + ow) * out_c + oc] = shannon_clamp_int8(acc);
            }
        }
    }
}

static void shannon_dwconv2d_int8(const int8_t* in, const int8_t* w, const int32_t* bias, int8_t* out,
                                 int in_h, int in_w, int channels, int out_h, int out_w,
                                 int kh, int kw, int stride) {
    for (int c = 0; c < channels; c++) {
        int32_t b = bias ? bias[c] : 0;
        const int8_t* w_c = &w[c * kh * kw];
        for (int oh = 0; oh < out_h; oh++) {
            int ih_base = oh * stride;
            for (int ow = 0; ow < out_w; ow++) {
                int iw_base = ow * stride;
                int32_t acc = b;
                for (int r = 0; r < kh; r++) {
                    int ih = ih_base + r;
                    if (ih < 0 || ih >= in_h) continue;
                    for (int col = 0; col < kw; col++) {
                        int iw = iw_base + col;
                        if (iw < 0 || iw >= in_w) continue;
                        int in_idx = (ih * in_w + iw) * channels + c;
                        int w_idx = r * kw + col;
                        acc += (int32_t)in[in_idx] * (int32_t)w_c[w_idx];
                    }
                }
                acc = acc >> 7;
                out[(oh * out_w + ow) * channels + c] = shannon_clamp_int8(acc);
            }
        }
    }
}

static void shannon_maxpool_int8(const int8_t* in, int8_t* out, int in_len, int stride) {
    int out_idx = 0;
    for (int i = 0; i < in_len; i += stride) {
        int8_t max_val = in[i];
        for (int k = 1; k < stride && (i + k) < in_len; k++) {
            if (in[i + k] > max_val) max_val = in[i + k];
        }
        out[out_idx++] = max_val;
    }
}

static void shannon_softmax_int8(const int8_t* in, float* out, int size) {
    int8_t max_val = in[0];
    for (int i = 1; i < size; i++) {
        if (in[i] > max_val) max_val = in[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        out[i] = expf((float)(in[i] - max_val) * 0.1f);
        sum += out[i];
    }
    if (sum > 0.0f) {
        for (int i = 0; i < size; i++) out[i] /= sum;
    }
}

// ===========================================================================
// MAIN INFERENCE ENTRYPOINT (ZERO DYNAMIC ALLOCATION)
// ===========================================================================
static inline int shannon_run_inference(const int8_t* input_data, int8_t* output_data) {
    if (!input_data || !output_data) return -1; // Null pointer check

    // Step 1: vis_conv1 [Conv2D]
    const int8_t* in_ptr_0 = input_data;
    int8_t* out_ptr_0 = (int8_t*)&shannon_tensor_arena[0];
    shannon_conv2d_int8(in_ptr_0, shannon_vis_conv1_weights, shannon_vis_conv1_bias, out_ptr_0, 24, 24, 1, 24, 24, 16, 3, 3, 2);

    // Step 2: vis_dw_conv [DepthwiseConv2D]
    const int8_t* in_ptr_1 = (const int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_1 = (int8_t*)&shannon_tensor_arena[9216];
    shannon_dwconv2d_int8(in_ptr_1, shannon_vis_dw_conv_weights, shannon_vis_dw_conv_bias, out_ptr_1, 24, 24, 16, 24, 24, 3, 3, 1);

    // Step 3: vis_pw_conv [Conv2D]
    const int8_t* in_ptr_2 = (const int8_t*)&shannon_tensor_arena[9216];
    int8_t* out_ptr_2 = (int8_t*)&shannon_tensor_arena[0];
    shannon_conv2d_int8(in_ptr_2, shannon_vis_pw_conv_weights, shannon_vis_pw_conv_bias, out_ptr_2, 24, 24, 16, 12, 12, 32, 1, 1, 2);

    // Step 4: vis_global_pool [MaxPool2D]
    const int8_t* in_ptr_3 = (const int8_t*)&shannon_tensor_arena[0];
    int8_t* out_ptr_3 = (int8_t*)&shannon_tensor_arena[4608];
    shannon_maxpool_int8(in_ptr_3, out_ptr_3, 4608, 12);

    // Step 5: vis_classifier [Dense]
    const int8_t* in_ptr_4 = (const int8_t*)&shannon_tensor_arena[4608];
    int8_t* out_ptr_4 = output_data;
    shannon_dense_int8(in_ptr_4, shannon_vis_classifier_weights, shannon_vis_classifier_bias, out_ptr_4, 32, 2);

    return 0; // Inference Execution Success
}

#ifdef __cplusplus
}
#endif

#endif // SHANNON_SHANNON_MICROVISION_REAL_H