/**
 * Shannon ESP32-S3 Edge AI Deployment Example
 * Zero-dependency real-time inference loop using the Shannon-generated header.
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_timer.h"
#include "esp_log.h"

// Include your autogenerated model header here
// #include "shannon_model.h"

static const char *TAG = "SHANNON_ESP32";

extern "C" void app_main(void)
{
    ESP_LOGI(TAG, "=================================================");
    ESP_LOGI(TAG, "⚡ Shannon Autonomous TinyML Engine Initialized");
    ESP_LOGI(TAG, "Target: ESP32-S3 (Xtensa Dual-Core 240MHz)");
    ESP_LOGI(TAG, "=================================================");

    // Mock input buffer (e.g. from microphone I2S or camera DVP)
    int8_t mock_input[490] = {0};
    int8_t mock_output[4] = {0};

    while (1) {
        int64_t start_time = esp_timer_get_time();

        // Run Shannon Inference
        // shannon_run_inference(mock_input, mock_output);

        int64_t duration_us = esp_timer_get_time() - start_time;

        ESP_LOGI(TAG, "Inference completed in %lld microseconds", duration_us);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}